# Generated by Django 5.1.6 on 2025-10-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='quilometragem',
        ),
    ]
